name: memes_manager
description: 一个用于收纳、分享表情包的软件
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.4.0
  intl: ^0.18.0
  logger: ^2.0.2
  riverpod_annotation: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
